# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161021_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(error_messages={'unique': 'The user with same username is already exists'}, max_length=30, unique=True),
        ),
    ]
