# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161023_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(error_messages={'unique': 'The user with same email is already exists'}, max_length=254, unique=True, verbose_name='mail'),
        ),
    ]
