# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20161023_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='mail'),
        ),
    ]
